name: Destroy Terraform Environment

on:
  workflow_dispatch:
    inputs:
      destroy_confirmation:
        description: 'Confirm Destroy (yes/no)'
        required: true
        default: 'no'

jobs:
  Destroy_Infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2

      - name: Terraform Init
        working-directory: ./Modules
        run: terraform init -input=false
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Confirm Destroy Action
        if: github.event.inputs.destroy_confirmation != 'yes'
        run: |
          echo "Destroy action not confirmed. Exiting..."
          exit 1

      - name: Destroy Infrastructure
        working-directory: ./Modules
        run: terraform destroy -auto-approve
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Confirm Success
        if: success()
        run: echo "Terraform Destroy Completed Successfully!"

      - name: Capture Failure
        if: failure()
        run: echo "Terraform Destroy Failed!" && exit 1